server:
  port: 8080
spring:
  sql:
    init:
      mode: always
      platform: h2
  application:
    name: evaluation
  datasource:
    url: jdbc:h2:file:./my-database
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop