INSERT INTO leagues (name, description, status) VALUES
('La Liga EA Sports', 'Primera división del fútbol profesional en España.', true),
('Premier League', 'Máxima categoría del sistema de ligas de fútbol de Inglaterra.', true),
('Serie A', 'Máxima categoría del sistema de ligas de fútbol de Italia.', true),
('Bundesliga', 'Competición entre los clubes de fútbol de la máxima categoría de Alemania.', true),
('Ligue 1', 'Máxima categoría del sistema de ligas de fútbol de Francia.', true),
('Champions League', 'Competición continental oficial de clubes organizada por la UEFA.', false);

INSERT INTO teams (name, league_id) VALUES
-- La Liga (league_id = 1)
('Real Madrid', 1), ('FC Barcelona', 1), ('Atlético de Madrid', 1), ('Sevilla FC', 1), ('Real Betis', 1),
('Real Sociedad', 1), ('Athletic Club', 1), ('Villarreal CF', 1), ('Valencia CF', 1), ('Girona FC', 1),
-- Premier League (league_id = 2)
('Manchester City', 2), ('Manchester United', 2), ('Liverpool FC', 2), ('Chelsea FC', 2), ('Arsenal FC', 2),
('Tottenham Hotspur', 2), ('Newcastle United', 2), ('Aston Villa', 2), ('West Ham United', 2), ('Brighton & Hove Albion', 2),
-- Serie A (league_id = 3)
('Juventus FC', 3), ('AC Milan', 3), ('Inter Milan', 3), ('SSC Napoli', 3), ('AS Roma', 3),
('Lazio', 3), ('Atalanta BC', 3), ('Fiorentina', 3), ('Torino FC', 3), ('Bologna FC', 3),
-- Bundesliga (league_id = 4)
('FC Bayern Munich', 4), ('Borussia Dortmund', 4), ('RB Leipzig', 4), ('Bayer 04 Leverkusen', 4), ('Eintracht Frankfurt', 4),
('Borussia Mönchengladbach', 4), ('VfL Wolfsburg', 4), ('SC Freiburg', 4), ('VfB Stuttgart', 4), ('Union Berlin', 4),
-- Ligue 1 (league_id = 5)
('Paris Saint-Germain', 5), ('Olympique de Marseille', 5), ('AS Monaco', 5), ('Olympique Lyonnais', 5), ('Lille OSC', 5),
('Stade Rennais FC', 5), ('OGC Nice', 5), ('RC Lens', 5), ('FC Nantes', 5), ('Stade de Reims', 5);

INSERT INTO players (name, surname, age, email, position, team_id) VALUES
('Jude', 'Bellingham', 22, 'j.bellingham@email.com', 'Centrocampista', 1),
('Lamine', 'Yamal', 18, 'l.yamal@email.com', 'Delantero', 2),
('Antoine', 'Griezmann', 34, 'a.griezmann@email.com', 'Delantero', 3),
('Youssef', 'En-Nesyri', 28, 'y.en-nesyri@email.com', 'Delantero', 4),
('Isco', 'Alarcón', 33, 'i.alarcon@email.com', 'Centrocampista', 5),
('Takefusa', 'Kubo', 24, 't.kubo@email.com', 'Delantero', 6),
('Nico', 'Williams', 23, 'n.williams@email.com', 'Delantero', 7),
('Gerard', 'Moreno', 33, 'g.moreno@email.com', 'Delantero', 8),
('José', 'Gaya', 30, 'j.gaya@email.com', 'Defensa', 9),
('Artem', 'Dovbyk', 28, 'a.dovbyk@email.com', 'Delantero', 10),
('Erling', 'Haaland', 25, 'e.haaland@email.com', 'Delantero', 11),
('Marcus', 'Rashford', 27, 'm.rashford@email.com', 'Delantero', 12),
('Mohamed', 'Salah', 33, 'm.salah@email.com', 'Delantero', 13),
('Cole', 'Palmer', 23, 'c.palmer@email.com', 'Centrocampista', 14),
('Bukayo', 'Saka', 24, 'b.saka@email.com', 'Delantero', 15),
('Son', 'Heung-min', 33, 's.heung-min@email.com', 'Delantero', 16),
('Bruno', 'Guimarães', 27, 'b.guimaraes@email.com', 'Centrocampista', 17),
('Ollie', 'Watkins', 29, 'o.watkins@email.com', 'Delantero', 18),
('Jarrod', 'Bowen', 28, 'j.bowen@email.com', 'Delantero', 19),
('Kaoru', 'Mitoma', 28, 'k.mitoma@email.com', 'Delantero', 20),
('Dušan', 'Vlahović', 25, 'd.vlahovic@email.com', 'Delantero', 21),
('Rafael', 'Leão', 26, 'r.leao@email.com', 'Delantero', 22),
('Lautaro', 'Martínez', 28, 'l.martinez@email.com', 'Delantero', 23),
('Victor', 'Osimhen', 26, 'v.osimhen@email.com', 'Delantero', 24),
('Paulo', 'Dybala', 31, 'p.dybala@email.com', 'Delantero', 25),
('Ciro', 'Immobile', 35, 'c.immobile@email.com', 'Delantero', 26),
('Teun', 'Koopmeiners', 27, 't.koopmeiners@email.com', 'Centrocampista', 27),
('Nicolás', 'González', 27, 'n.gonzalez@email.com', 'Delantero', 28),
('Duván', 'Zapata', 34, 'd.zapata@email.com', 'Delantero', 29),
('Joshua', 'Zirkzee', 24, 'j.zirkzee@email.com', 'Delantero', 30),
('Harry', 'Kane', 32, 'h.kane@email.com', 'Delantero', 31),
('Marco', 'Reus', 36, 'm.reus@email.com', 'Centrocampista', 32),
('Xavi', 'Simons', 22, 'x.simons@email.com', 'Centrocampista', 33),
('Florian', 'Wirtz', 22, 'f.wirtz@email.com', 'Centrocampista', 34),
('Mario', 'Götze', 33, 'm.gotze@email.com', 'Centrocampista', 35),
('Alassane', 'Pléa', 32, 'a.plea@email.com', 'Delantero', 36),
('Jonas', 'Wind', 26, 'j.wind@email.com', 'Delantero', 37),
('Vincenzo', 'Grifo', 32, 'v.grifo@email.com', 'Centrocampista', 38),
('Serhou', 'Guirassy', 29, 's.guirassy@email.com', 'Delantero', 39),
('Robin', 'Gosens', 31, 'r.gosens@email.com', 'Defensa', 40),
('Kylian', 'Mbappé', 26, 'k.mbappe@email.com', 'Delantero', 41),
('Pierre-Emerick', 'Aubameyang', 36, 'p.aubameyang@email.com', 'Delantero', 42),
('Wissam', 'Ben Yedder', 35, 'w.benyedder@email.com', 'Delantero', 43),
('Alexandre', 'Lacazette', 34, 'a.lacazette@email.com', 'Delantero', 44),
('Jonathan', 'David', 25, 'j.david@email.com', 'Delantero', 45),
('Martin', 'Terrier', 28, 'm.terrier@email.com', 'Delantero', 46),
('Khéphren', 'Thuram', 24, 'k.thuram@email.com', 'Centrocampista', 47),
('Elye', 'Wahi', 22, 'e.wahi@email.com', 'Delantero', 48),
('Mostafa', 'Mohamed', 27, 'm.mohamed@email.com', 'Delantero', 49),
('Junya', 'Ito', 32, 'j.ito@email.com', 'Delantero', 50);